import math
import torch
import torch.nn as nn
import torch.nn.functional as F

from timm.layers import use_fused_attn

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


class CrossAttention(nn.Module):
    
    def __init__(self, dim, num_heads=8, qkv_bias=False, attn_drop=0., proj_drop=0., init_std=0.02):
        super().__init__()

        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = head_dim ** -0.5

        self.projq = nn.Linear(dim, dim, bias=qkv_bias)
        self.projk = nn.Linear(dim, dim, bias=qkv_bias)
        self.projv = nn.Linear(dim, dim, bias=qkv_bias)
        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim)
        self.proj_drop = nn.Dropout(proj_drop)
        self.fused_attn = use_fused_attn()
        print("Attention: use_fused_attn =", self.fused_attn)

        #self.init_std = init_std
        #self.apply(self._init_weights)

    def _init_weights(self, m):
        """Initialize weights (truncated normal for Linear & Conv2d, constants for bias/norm)."""
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=self.init_std)
            if m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)
        elif isinstance(m, nn.Conv2d):
            trunc_normal_(m.weight, std=self.init_std)
            if m.bias is not None:
                nn.init.constant_(m.bias, 0)
    
    #@torch.compile
    def forward(self, query, key, value):
        B, Nq, C = query.shape
        Nk = key.shape[1]
        Nv = value.shape[1]

        q = self.projq(query).reshape(B,Nq,self.num_heads, C// self.num_heads).permute(0, 2, 1, 3)
        k = self.projk(key).reshape(B,Nk,self.num_heads, C// self.num_heads).permute(0, 2, 1, 3)
        v = self.projv(value).reshape(B,Nv,self.num_heads, C// self.num_heads).permute(0, 2, 1, 3)

        x = F.scaled_dot_product_attention(
                q, k, v,
                dropout_p=self.attn_drop.p if self.training else 0.,
        )

        x = x.transpose(1, 2).reshape(B, Nq, C)
        x = self.proj(x)
        x = self.proj_drop(x)

        return x

class CrossAttentionProbe(nn.Module):

    def __init__(self, dim, num_queries, with_norm=False, downscale=1, init_std=0.02):
        super().__init__()

        #self.queries = nn.Parameter(torch.zeros(1, num_queries, dim))
        self.queries = nn.Parameter(0.1 * torch.randn(1, num_queries, dim) / dim)
        self.downscale = downscale

        self.cross_attn = CrossAttention(dim)

        self.norm = nn.LayerNorm(dim) if with_norm else nn.Identity()
        self.norm1 = nn.LayerNorm(dim) if with_norm else nn.Identity()
        self.norm2 = nn.LayerNorm(dim) if with_norm else nn.Identity()

        #self.init_std = init_std
        #trunc_normal_(self.queries, std=self.init_std)

    def parameters(self, lr, weight_decay, lr_mult, wd_mult):
        return [{"params": self.cross_attn.parameters(), "lr": lr, "weight_decay": weight_decay},
                {"params": self.queries,                 "lr": lr, "weight_decay": weight_decay},
                {"params": self.norm.parameters(),       "lr": lr, "weight_decay": weight_decay},
                {"params": self.norm1.parameters(),      "lr": lr, "weight_decay": weight_decay},
                {"params": self.norm2.parameters(),      "lr": lr, "weight_decay": weight_decay}]


    def forward(self, x_orig):
        B,C,H,W = x_orig.shape

        Hx = H // self.downscale
        Wx = W // self.downscale

        x = F.interpolate(x_orig, (Hx, Wx), mode="bilinear")
        x = x.flatten(-2).movedim(1, -1)
        x_norm = self.norm(x)

        queries = self.norm1(self.queries).repeat(B, 1, 1)

        y = self.cross_attn(queries, x_norm, x_norm)
        y = self.norm2(y)

        xo = x_orig.flatten(-2).movedim(1, -1)
        xo = self.norm(xo)

        z = torch.einsum('bnd,bkd->bkn', xo, y) / C #**0.5

        z = z.unflatten(-1, (H, W))

        return z

class AttentionProbing(nn.Module):

    def __init__(
            self,
            device: torch.device,
            checkpoint='',
            combine_mode=None,  # How to combine (e.g., concat, sum, mean, etc.)
            name='norm_linear',
            num_queries=10,
            lr_norm_mult=10.,
            wd_norm_mult=0.,
            with_norm=False,
            downscale=1
    ):
        super().__init__(
            device,
            checkpoint,
            combine_mode
        )
        self.name = f'{name}_{combine_mode}'
        self.lr_norm_mult = lr_norm_mult
        self.wd_norm_mult = wd_norm_mult
        self.with_norm = with_norm
        self.downscale = downscale

    def parameters(self, lr, weight_decay):
        params = [{"params": self.probe.parameters(), "lr": lr, "weight_decay": weight_decay}]
        return params

    def create_probe(self, input_dim, output_dim):
        return self.probe

    def apply_probe(self, probe: nn.Module, feats: torch.Tensor):
        return probe(feats)

    def forward(self, feats):
        b,c,h,w = feats[-1].shape

        logits_lr = self.probe[0](feats[0])
        logits_lr = F.interpolate(logits_lr, (h, w), mode="bilinear", align_corners=False)

        logits_hr = self.probe[1](feats[1])

        return logits_lr + logits_hr

    def setup(self, input_dim, output_dim):

        self.output_dim = output_dim

        # If we want to combine at logits stage the input must be multiple layers or models
        assert isinstance(input_dim, (tuple, list))
        self.input_dim = input_dim

        self.probe = nn.ModuleList()

        # standard linear for dim0
        self.probe.append(nn.Conv2d(input_dim[0], output_dim, 1))

        if len(input_dim) > 1:
            assert len(input_dim) == 2
            self.probe.append(CrossAttentionProbe(input_dim[1], output_dim, self.with_norm, self.downscale))

        if self.checkpoint:
            self.load_weights(self.checkpoint)
